projects:
  gameoflife-core:
    git_url:
        - "gameoflife-core.git"
  gameoflife-deploy:
    git_url:
        - "gameoflife-deploy.git"
  gameoflife-web:
     git_url:
        - "gameoflife-web.git"
